# Generated by Django 2.0.7 on 2019-01-16 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.IntegerField(choices=[(0, 'char'), (1, 'word'), (2, 'line')])),
                ('image', models.ImageField(upload_to='box')),
                ('left', models.DecimalField(decimal_places=4, max_digits=5)),
                ('top', models.DecimalField(decimal_places=4, max_digits=5)),
                ('right', models.DecimalField(decimal_places=4, max_digits=5)),
                ('bottom', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BoxTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='training.Box')),
            ],
        ),
        migrations.CreateModel(
            name='OCRSearchRequestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_request_id', models.CharField(max_length=100)),
                ('orig_image_key', models.UUIDField()),
                ('image_url', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('valid', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OCRSearchRequestSourceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='training.OCRSearchRequestSource')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='training.OCRSearchRequestSource'),
        ),
    ]
