# Generated by Django 2.0.7 on 2018-09-04 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRSearchRequestBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='box')),
                ('left', models.DecimalField(decimal_places=4, max_digits=4)),
                ('top', models.DecimalField(decimal_places=4, max_digits=4)),
                ('right', models.DecimalField(decimal_places=4, max_digits=4)),
                ('bottom', models.DecimalField(decimal_places=4, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mathpix_latex', models.CharField(blank=True, max_length=500)),
                ('latex', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OCRSearchRequestSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_request_id', models.CharField(max_length=100)),
                ('image_key', models.UUIDField()),
                ('user_id', models.IntegerField()),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('grade_category', models.IntegerField(blank=True, choices=[(1, '초'), (2, '중'), (3, '고')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ocrsearchrequestbox',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='source.OCRSearchRequestSource'),
        ),
    ]
