# Generated by Django 2.0.7 on 2018-12-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_auto_20181116_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrsearchrequestbox',
            name='bottom',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ocrsearchrequestbox',
            name='left',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ocrsearchrequestbox',
            name='right',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ocrsearchrequestbox',
            name='top',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
