# Generated by Django 2.1.1 on 2018-12-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_boxing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='mathpix_latex',
        ),
        migrations.AddField(
            model_name='box',
            name='label',
            field=models.IntegerField(choices=[(1, 'word'), (2, 'picture'), (3, 'graph')], default=1),
            preserve_default=False,
        ),
    ]
