# Generated by Django 2.1.1 on 2018-12-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_boxing', '0002_auto_20181226_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='label',
            field=models.IntegerField(choices=[(1, 'wod'), (2, 'picture'), (3, 'graph')]),
        ),
    ]
