# Generated by Django 2.1.1 on 2018-12-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_auto_20181220_0919'),
        ('picture_boxing', '0003_auto_20181227_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='source',
            name='grade_category',
        ),
        migrations.AddField(
            model_name='source',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='source.OCRSearchRequestSource'),
        ),
        migrations.AddField(
            model_name='source',
            name='valid',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='label',
            field=models.IntegerField(choices=[(1, 'word'), (2, 'picture'), (3, 'graph')]),
        ),
    ]
