# Generated by Django 2.1.1 on 2018-12-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_boxing', '0004_auto_20181227_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='source',
        ),
        migrations.RemoveField(
            model_name='source',
            name='valid',
        ),
        migrations.AddField(
            model_name='source',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='grade_category',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
    ]
