# Generated by Django 2.1.1 on 2018-12-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_boxing', '0005_auto_20181227_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='valid',
            field=models.NullBooleanField(),
        ),
    ]
