# Generated by Django 2.0.7 on 2018-12-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0004_auto_20181220_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='QalculatorBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='box')),
                ('left', models.DecimalField(decimal_places=4, max_digits=5)),
                ('top', models.DecimalField(decimal_places=4, max_digits=5)),
                ('right', models.DecimalField(decimal_places=4, max_digits=5)),
                ('bottom', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_text', models.CharField(help_text='Boxing UI에서 입력한 값', max_length=200)),
                ('unicode_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QalculatorBoxTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='hangul_qalculator.QalculatorBox')),
            ],
        ),
        migrations.CreateModel(
            name='QalculatorSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_request_id', models.CharField(max_length=100)),
                ('image_key', models.UUIDField()),
                ('user_id', models.IntegerField()),
                ('valid', models.NullBooleanField()),
                ('ocrsr_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qalculator', to='source.OCRSearchRequestSource')),
            ],
        ),
        migrations.AddField(
            model_name='qalculatorbox',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='hangul_qalculator.QalculatorSource'),
        ),
    ]
